services:
  subtitles:
    image: subtitles
    container_name: subtitles
    environment:
      BAZARR_URL: SUA_URL_BAZARR
      BAZARR_API_KEY: SUA_CHAVE_API_BAZARR
      NOTIFICATION_URL: SUA_URL_NOTIFICACAO
    build:
      context: .
